# -*- coding: utf-8 -*-
"""Infectious Day 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gk7C7iP99kdESJOjqV4teiht4QLGfR4o
"""

#Write a Python function parity that returns ‘EVEN‘ if a number is even,
#‘ODD‘ if a number is odd, and ‘badInput‘ if any other input is given. Then write a loop
#that loops through the first 20 Fibonacci numbers, and prints the output of parity for each
#Fibonacci number. (Note: you must call parity; don’t just recreate its functionality inside your loop.)
print()
print("Even/odd function")


def parity(n):
  if n % 2 == 0:
    return "even"
  if n % 2 == 1:
    return "odd"
  if type(n) != int:
    return "badInput"
  else:
    return "badInput"

print("7 is", parity(7)) #returns odd
print("4 is", parity(4)) #returns even
print("a non-whole number is a", parity(4.5)) #returns badInput

fibo_list = [1,1]

def fibo(nth):
  while len(fibo_list) < nth:
    fibo_list.append((fibo_list[-1]+fibo_list[-2]))
  return fibo_list
print("The First 20 Fibonacci Numbers are:", fibo(20))

test_input_str = input("Give me a number, and I'll tell you if it's even or odd: ")

if type(test_input_str) == int:
  test_input_num = float(test_input_str)
  if test_input_num % 1 == 0:
    test_input_int = int(test_input_num)
    print(test_input_int, "is", parity(test_input_int))
  else:
    print(test_input_str, "is a badInput")
else:
  print(test_input_str, "is a badInput")


#https://projecteuler.net/problem=12

def triangle_number_but_faster(n):
  return(n * (n+1) / 2) #sum of the first n whole numbers is n*(n+1)/2

def find_number_of_factors(n):
  number_of_factors = 0
  for i in range(1, n+1):
    if (n / i) % 1 == 0: #if a number is evenly divisible by one, it is an integer. Otherwise, it is not
      number_of_factors = number_of_factors + 1
  return(number_of_factors)

counter_variable = 0
total_divisors = 2

while total_divisors < 500:
  if counter_variable % 2 == 0:
    counter_variable = round(counter_variable)
    total_divisors = find_number_of_factors(counter_variable // 2) * find_number_of_factors(counter_variable + 1) # divisors of a*b= divisors of a * divisors of b, if a and b are coprime. counter_variable and counter_variable + 1 are coprime because they are exactly one apart. Also, the triangle number is n*(n+1)/2 and between n and n+1, one of them has to be even so I am just finding the one that's even and dividing that by 2 before finding the number of factors
    print("triangle number", counter_variable, "has", total_divisors, "divisors")
    if total_divisors >= 500:
      total_divisors = 600 #stop
    if total_divisors < 500:
      counter_variable = counter_variable + 1
  if counter_variable % 2 == 1:
    counter_variable = round(counter_variable)
    total_divisors = find_number_of_factors(counter_variable) * find_number_of_factors((counter_variable + 1) // 2)
    print("triangle number", counter_variable, "has", total_divisors, "divisors")
    if total_divisors >= 500:
      total_divisors = 600 #stop
    if total_divisors < 500:
      counter_variable = counter_variable + 1

print()
print()
print()
print("Project Euler Problem 12")
print("The first triangle number with 500+ factors is", round(triangle_number_but_faster(counter_variable)), ", the", counter_variable, "th triangle number, which has", total_divisors, "factors")




#a solution attempt that took way too long


#  if (find_number_of_factors(counter_variable) + find_number_of_factors(counter_variable + 1) - 1) >= 500:
 #   print("The first triangle number to have 500 factors is", triangle_number_but_faster(n), "which has", n, "factors")
  #if (find_number_of_factors(counter_variable) + find_number_of_factors(counter_variable + 1) - 1) < 500:
   # print(counter_variable)
    #print("total factors should be", (find_number_of_factors(counter_variable) + find_number_of_factors(counter_variable + 1) - 1))
    #print()
    #counter_variable = counter_variable + 1
#def triangle_number(n):
#  triangle = 0
#  for i in range(1, n+1):
#    triangle = triangle + i
#  return(triangle)
#print("triangle number 7 is", triangle_number(7))
#def find_number_of_factors(n):
#  number_of_factors = 0
#  for i in range(1, n+1):
#    if (n / i) % 1 == 0:
#      number_of_factors = number_of_factors + 1
#  return(number_of_factors)
#print(triangle_number(7))
#print(find_number_of_factors(triangle_number(7)))

#factors_of_triangle_number = 0
#j = 1

#while factors_of_triangle_number < 500:
#  factors_of_triangle_number = find_number_of_factors(triangle_number(j))
#  j = j + 1
#  print(j)
#  print(triangle_number(j))
#print()
#print()
#print(j)
#print(triangle_number(j))





print()

#https://projecteuler.net/problem=16
print("Project Euler Problem 16")

exp = pow(2,1000)

def digit_sum(num_to_sum):
  counter = len(str(num_to_sum))
  sum_of_digits = 0
  while counter+1 > 0:
    smallest_digit = num_to_sum % 10
    sum_of_digits = sum_of_digits + smallest_digit
    num_to_sum = num_to_sum // 10
    counter = counter - 1
  return(sum_of_digits)

print("The sum of the digits of 2^1000 is", digit_sum(exp))

#https://projecteuler.net/problem=15
print()
print("Project Euler Problem 15")

#this is just a combinatorics problem, since you move to the right 20 times and down 20 times. You need to pick 20/40 turns to go right, so 40 choose 20.

def factorial(num_to_factorial):
  factorial_answer = 1
  for i in range (1, num_to_factorial + 1):
    factorial_answer = factorial_answer * i
  return(factorial_answer)

def n_choose_r(n,r):
  return(factorial(n) / (factorial(r) * factorial(n - r)))

print("The number of different paths is", round(n_choose_r(40,20)))

