# -*- coding: utf-8 -*-
"""infectious day 9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13KaCY1Rb28xRQiHvflrBBm0CbfQw9RQg
"""

# Aidin and Nate A.

import matplotlib.pyplot as plt

def next_step(*, S_previous, \
              I_previous, \
              R_previous, \
              R0, \
              D, \
              time_step_length):
  #your code here; calculate the next values of S, I, and R,
  #and assign them to the variables S_next, I_next, and R_next

  # S_to_I is the number of people who transition from susceptible to infected in one time step.
  # I_to_R is the number of people who transition from infected to removed in one time step.
  S_to_I = (R0 * S_previous * I_previous) / (D * (S_previous + I_previous + R_previous))
  I_to_R = I_previous / D

  S_next = S_previous - S_to_I
  I_next = I_previous + S_to_I - I_to_R
  R_next = R_previous + I_to_R
  return S_next, I_next, R_next

def SIR(*, S_initial, \
        I_initial, \
        R_initial, \
        R0, \
        D, \
        time_step_length, \
        num_steps):
  #your code here; call the function next_step and create
  #lists of the times when you calculate steps,
  #the number of susceptible people at every time step,
  #the number of infected people at every time step, and
  #the number of removed people at every time step

  susceptible_list = []
  infected_list = []
  removed_list = []
  time_list = []
  for k in range(0, num_steps, time_step_length):
    time_list.append(k)

  S_previous = S_initial
  I_previous = I_initial
  R_previous = R_initial

  for i in (time_list):
    S_next, I_next, R_next = next_step(S_previous = S_previous, I_previous = I_previous, R_previous = R_previous, R0 = R0, D = D, time_step_length = time_step_length)

    susceptible_list.append(S_previous)
    infected_list.append(I_previous)
    removed_list.append(R_previous)

    S_previous = S_next
    I_previous = I_next
    R_previous = R_next



  return time_list, susceptible_list, infected_list, removed_list

time_list, susceptible_list, infected_list, removed_list = SIR(S_initial = 99999, I_initial = 1, R_initial = 0, R0 = 3, D = 5, time_step_length = 1, num_steps = 50)


def draw_graph(*, time_list, \
               susceptible_list, \
               infected_list, \
               removed_list):
  fig = plt.figure()
  plt.plot(time_list, susceptible_list, label='susceptibles')
  plt.plot(time_list, removed_list, label='removed')
  plt.plot(time_list, infected_list, label='infected')
  plt.xlabel("Time (days)")
  plt.ylabel("Each Group Population")
  plt.legend(loc='lower right')
  plt.title("SIR Model, R₀=3")
  plt.show()
  return

draw_graph(time_list = time_list, susceptible_list = susceptible_list, infected_list = infected_list, removed_list = removed_list)