# -*- coding: utf-8 -*-
"""infectious day 11

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UCr4RAU-ai7U-DxhqHVS5lTYiuQO-fM3
"""

import matplotlib.pyplot as plt


def next_step(*, S_previous, \
              I_previous, \
              R_previous, \
              R0, \
              D, \
              time_step_length):
  #your code here; calculate the next values of S, I, and R,
  #and assign them to the variables S_next, I_next, and R_next
  N = 100000

  # S_to_I is the number of people who transition from susceptible to infected in one time step.
  S_to_I = I_previous*time_step_length*((R0/D)*(S_previous/N))

  # I_to_R is the number of people who transition from infected to removed in one time step.
  I_to_R = (I_previous/D)*time_step_length

  S_next = S_previous-S_to_I
  I_next = I_previous+S_to_I-I_to_R
  R_next = R_previous+I_to_R

  return S_next, I_next, R_next

def SIR(*, S_initial, \
        I_initial, \
        R_initial, \
        R0, \
        D, \
        time_step_length, \
        num_steps):
  #your code here; call the function next_step and create
  #lists of the times when you calculate steps,
  #the number of susceptible people at every time step,
  #the number of infected people at every time step, and
  #the number of removed people at every time step

  susceptible_list = [S_initial]
  infected_list = [I_initial]
  removed_list = [R_initial]
  time_list = [0]
  for k in range(1, num_steps):
    time_list.append(k)
    new_susceptible, new_infected, new_removed = next_step(S_previous=susceptible_list[-1], I_previous=infected_list[-1], R_previous=removed_list[-1], R0=R0, D=D, time_step_length=time_step_length)
    susceptible_list.append(new_susceptible)
    infected_list.append(new_infected)
    removed_list.append(new_removed)

  return time_list, susceptible_list, infected_list, removed_list

def draw_graph(*, time_list, \
               susceptible_list, \
               infected_list, \
               removed_list):
  fig = plt.figure()
  plt.plot(time_list, susceptible_list, label='susceptibles')
  plt.plot(time_list, infected_list, label='infected')
  plt.plot(time_list, removed_list, label='removed')
  plt.xlabel("")
  plt.ylabel("")
  plt.legend(loc='lower right')
  plt.show()
  return

time_list, susceptible_list, infected_list, removed_list=SIR(S_initial=99999, I_initial=1, R_initial=0, R0=3, D=5, time_step_length=1, num_steps=1000)
draw_graph(time_list=time_list, susceptible_list=susceptible_list, infected_list=infected_list, removed_list=removed_list)

time_list, susceptible_list, infected_list, removed_list=SIR(S_initial=99999, I_initial=1, R_initial=0, R0=3, D=5, time_step_length=10, num_steps=1000)
draw_graph(time_list=time_list, susceptible_list=susceptible_list, infected_list=infected_list, removed_list=removed_list)

time_list, susceptible_list, infected_list, removed_list=SIR(S_initial=99999, I_initial=1, R_initial=0, R0=3, D=5, time_step_length=0.1, num_steps=1000)
draw_graph(time_list=time_list, susceptible_list=susceptible_list, infected_list=infected_list, removed_list=removed_list)

time_list, susceptible_list, infected_list, removed_list=SIR(S_initial=99999, I_initial=1, R_initial=0, R0=3, D=5, time_step_length=0.01, num_steps=1000)
draw_graph(time_list=time_list, susceptible_list=susceptible_list, infected_list=infected_list, removed_list=removed_list)