# -*- coding: utf-8 -*-
"""Infectious Day 17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hh0eIMnGphs6ocGur2JJqR-eHfs-4yog

#Infectious Diseases Day 17: Evolution of Disease Variants
"""

import matplotlib.pyplot as plt

def next_step(*, S_previous, \
              Iw_previous, \
              Im_previous, \
              Rw_previous, \
              Rm_previous, \
              R0, \
              D, \
              M, \
              time_step_length):
  #your code here; calculate the next values of S, I, and R,
  #and assign them to the variables S_next, I_next, and R_next

  # S_to_I is the number of people who transition from susceptible to infected in one time step.
  # I_to_R is the number of people who transition from infected to removed in one time step.
  S_to_Iw = (R0 * S_previous * Iw_previous) / (D * (S_previous + Iw_previous + Im_previous + Rw_previous + Rm_previous))
  S_to_Im = (R0 * S_previous * Im_previous) / (D * (S_previous + Iw_previous + Im_previous + Rw_previous + Rm_previous))
  Iw_to_Im = Iw_previous * M / D
  Iw_to_Rw = Iw_previous / D * (1-M)
  Rw_to_Im = (R0 * Im_previous * Rw_previous) / (D * (S_previous + Iw_previous + Im_previous + Rw_previous + Rm_previous))
  Im_to_Rm =Im_previous / D

  S_next = S_previous - S_to_Iw - S_to_Im
  Iw_next = Iw_previous + S_to_Iw - Iw_to_Rw - Iw_to_Im
  Im_next = Im_previous + S_to_Im + Iw_to_Im + Rw_to_Im - Im_to_Rm
  Rw_next = Rw_previous + Iw_to_Rw - Rw_to_Im
  Rm_next = Rm_previous + Im_to_Rm
  return S_next, Iw_next, Rw_next, Im_next, Rm_next

def SIR(*, S_initial, \
        Iw_initial, \
        Im_initial, \
        Rw_initial, \
        Rm_initial, \
        R0, \
        D, \
        M, \
        time_step_length, \
        num_steps):
  #your code here; call the function next_step and create
  #lists of the times when you calculate steps,
  #the number of susceptible people at every time step,
  #the number of infected people at every time step, and
  #the number of removed people at every time step

  susceptible_list = []
  iw_list = []
  im_list = []
  rw_list = []
  rm_list = []
  time_list = []
  for k in range(0, num_steps, time_step_length):
    time_list.append(k)

  S_previous = S_initial
  Iw_previous = Iw_initial
  Im_previous = Im_initial
  Rw_previous = Rw_initial
  Rm_previous = Rm_initial

  for i in (time_list):
    S_next, Iw_next, Rw_next, Im_next, Rm_next = next_step(S_previous = S_previous, \
                                                           Iw_previous = Iw_previous, \
                                                           Im_previous = Im_previous, \
                                                           Rw_previous = Rw_previous, \
                                                           Rm_previous = Rm_previous, \
                                                           R0 = R0, \
                                                           D = D, \
                                                           M = M, \
                                                           time_step_length = time_step_length)
    susceptible_list.append(S_previous)
    iw_list.append(Iw_previous)
    im_list.append(Im_previous)
    rw_list.append(Rw_previous)
    rm_list.append(Rm_previous)

    S_previous = S_next
    Iw_previous = Iw_next
    Im_previous = Im_next
    Rw_previous = Rw_next
    Rm_previous = Rm_next


  return time_list, susceptible_list, iw_list, im_list, rw_list, rm_list



time_list, susceptible_list, iw_list, im_list, rw_list, rm_list = SIR(S_initial = 99999, \
                                                                      Iw_initial = 1, \
                                                                      Im_initial = 0, \
                                                                      Rw_initial = 0, \
                                                                      Rm_initial = 0, \
                                                                      R0 = 3, \
                                                                      D = 3, \
                                                                      M = 1 / 1000000, \
                                                                      time_step_length = 1, \
                                                                      num_steps = 71)

def draw_graph(*, time_list, \
               susceptible_list, \
               iw_list, \
               im_list, \
               rw_list, \
               rm_list):
  fig = plt.figure()
  plt.plot(time_list, susceptible_list, label='Susceptible')
  plt.plot(time_list, iw_list, label='Infected with Wild Strain')
  plt.plot(time_list, im_list, label='Infected with Mutated Strain')
  plt.plot(time_list, rw_list, label='Immune to Wild Strain')
  plt.plot(time_list, rm_list, label='Immune to Both')
  plt.xlabel("Time (days)")
  plt.ylabel("Each Group's Population")
  plt.legend(loc='upper left')
  plt.title("Evolution of Disease Variants Model")
  fig.set_size_inches(9, 4)
  plt.show()
  return

draw_graph(time_list = time_list, 
           susceptible_list = susceptible_list, 
           iw_list = iw_list, 
           im_list = im_list, 
           rw_list = rw_list, 
           rm_list = rm_list)


#some interesting data points
print()
print("After", time_list[-1], "days:")
print(round(susceptible_list[-1]), "people are susceptible to both viruses \n")
print(round(iw_list[-1]), "people are infected with the wild type virus")
print(round(rw_list[-1]), "people are recovered from the wild type virus \n")
print(round(im_list[-1]), "people are infected with the mutated virus")
print(round(rm_list[-1]), "people are recovered from the mutated virus \n")


#print("The last person infected with either virus strain would recover after 145 days, with \
#\n~95% being immune to both, \n~4.5% being recovered from just the wild strain, and only \
#\n~0.2% of the 100,000 having been never infected with either virus.")
