# -*- coding: utf-8 -*-
"""infectious day 14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bTbuQD_WAlGziFfqUONcS9ck7NcChVgH

#Infectious Disease Modeling Day 14, 15, and 16 --- Agent Based Models
###Nate A and Hannah

#Model 1
"""

import random
import numpy as np
import matplotlib.pyplot as plt
population_list = ['I']

for i in range (99):
  population_list.append('S')

def next_step(population_list, R0, D):
  S_to_I = (population_list.count('I')*R0/(D*100))
  I_to_R = (1/D)
  items_S = ['S', 'I']
  weights_S = [(1-S_to_I), S_to_I]
  items_I = ['I', 'R']
  weights_I = [(1-I_to_R), I_to_R]
  population_next=[]
  for i in range (100):
    if population_list[i]=='S':
      population_next.append (np.random.choice(items_S, p=weights_S)[0])
    if population_list[i]=='I':
      population_next.append (np.random.choice(items_I, p=weights_I)[0])
    if population_list[i]=='R':
      population_next.append('R')
  return population_next

S_list=[]
I_list=[]
R_list=[]

for i in range(50):
  S_list.append(population_list.count('S'))
  I_list.append(population_list.count('I'))
  R_list.append(population_list.count('R'))
  population_list=next_step(population_list, R0=3, D=5)

time_list=[]
for i in range(50):
  time_list.append(i)


def draw_graph(*, time_list, \
               susceptible_list, \
               infected_list, \
               removed_list):
  fig = plt.figure()
  plt.plot(time_list, susceptible_list, label='Susceptible')
  plt.plot(time_list, infected_list, label='Infected')
  plt.plot(time_list, removed_list, label='Removed')
  plt.xlabel("Days")
  plt.ylabel("People")
  plt.legend(loc='lower right')
  plt.title("Model 1: Agent-Based")
  plt.show()
  return

draw_graph(time_list=time_list, susceptible_list=S_list, infected_list=I_list, removed_list=R_list)

next_step(population_list, R0=3, D=5)
print(population_list)

"""#Model 2"""

import random
import numpy as np
import matplotlib.pyplot as plt

population_size = 100
population_counts = [population_size - 1, 1, 0]

def next_step(current_counts, R0, D, N):
  S = current_counts[0]
  I = current_counts[1]
  R = current_counts[2]

  prob_S_to_I = (R0 / D) * (I / N) if I > 0 else 0
  next_infected = np.random.binomial(S, prob_S_to_I)
  next_infected = min(next_infected, S)

  prob_I_to_R = 1 / D
  next_recovered = np.random.binomial(I, prob_I_to_R)
  next_recovered = min(next_recovered, I)

  next_S = S - next_infected
  next_I = I + next_infected - next_recovered
  next_R = R + next_recovered

  return [next_S, next_I, next_R]

S_list=[]
I_list=[]
R_list=[]

for i in range(50):
  S_list.append(population_counts[0])
  I_list.append(population_counts[1])
  R_list.append(population_counts[2])
  population_counts = next_step(population_counts, R0=3, D=5, N=population_size)

time_list=[]
for i in range(50):
  time_list.append(i)

def draw_graph(*, time_list, \
               susceptible_list, \
               infected_list, \
               removed_list):
  fig = plt.figure()
  plt.plot(time_list, susceptible_list, label='Susceptible')
  plt.plot(time_list, infected_list, label='Infected')
  plt.plot(time_list, removed_list, label='Removed')
  plt.xlabel("Days")
  plt.ylabel("People")
  plt.legend(loc='lower right')
  plt.title("Model 2: Without Agents")
  plt.show()
  return

draw_graph(time_list=time_list, susceptible_list=S_list, infected_list=I_list, removed_list=R_list)

print(population_counts)

"""#Model 3

"""

import random
import numpy as np
import matplotlib.pyplot as plt

population_list = ['I']

for i in range (99):
  population_list.append('S')

def next_step(population_list, R0, D, contacts_per_day):
  population_size = len(population_list)
  new_population_list = list(population_list)
  prob_S_to_I_per_contact = R0 / (D * contacts_per_day)


#step 1: infected person might infect more people
  for i in range(population_size):
    if population_list[i] == 'I':
      for j in range(contacts_per_day):
        contact_person_index = random.randint(0, population_size - 1) #contact is a random person in the population
        if population_list[contact_person_index] == 'S':
          if random.random() < prob_S_to_I_per_contact:
            new_population_list[contact_person_index] = 'I'

#step 2: infected person might recover
  for i in range(population_size):
    if population_list[i] == 'I':
      if random.random() < (1/D): #picks a random number 0-1, if that is less than prob_I_to_R then the infected person becomes recovered
        new_population_list[i] = 'R'

  return new_population_list




S_list=[]
I_list=[]
R_list=[]
contacts_per_day = 10

for i in range(50):
  S_list.append(population_list.count('S'))
  I_list.append(population_list.count('I'))
  R_list.append(population_list.count('R'))
  population_list=next_step(population_list, R0=3, D=5, contacts_per_day = 10)

time_list=[]
for i in range(50):
  time_list.append(i)


def draw_graph(*, time_list, \
               susceptible_list, \
               infected_list, \
               removed_list):
  fig = plt.figure()
  plt.plot(time_list, susceptible_list, label='Susceptible')
  plt.plot(time_list, infected_list, label='Infected')
  plt.plot(time_list, removed_list, label='Removed')
  plt.xlabel("Days")
  plt.ylabel("People")
  plt.legend(loc='lower right')
  plt.title("Model 3: Stochastic Contacts")
  plt.show()
  return

draw_graph(time_list=time_list, susceptible_list=S_list, infected_list=I_list, removed_list=R_list)