# -*- coding: utf-8 -*-
"""Infectious Day 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWc_LW6paxWU1AchpbAiMEL-rtPIvsHu
"""

#Nate Arkin coding task one due 1/20
print("Loops")

#prints the numbers from 1-100
for a in range (1,101):
  print(a)

print()

#makes a list of numbers from 1-100, then prints that list
hundred_numbers_list = []
for b in range (1,101):
  hundred_numbers_list.append(b)
print(hundred_numbers_list)

print()

#first 20 fibonacci numbers
fibo_list = [1,1]
def fibo(nth):
  while len(fibo_list) < nth:
    fibo_list.append((fibo_list[-1]+fibo_list[-2]))
  return fibo_list
print("The First 20 Fibonacci Numbers are:", fibo(20))



print()
print()


#some more practice...
print("Problem 6") #https://projecteuler.net/problem=6
sum_of_squares = 0
square_of_sum = 0
for i in range (1,101):
  sum_of_squares = sum_of_squares + i*i
  square_of_sum = square_of_sum + i
square_of_sum = pow(square_of_sum,2)
difference = round(square_of_sum - sum_of_squares)
print("The difference is", difference)

print()

print("Problem 20") #https://projecteuler.net/problem=20
factorial = 1
for j in range (1,101):
  factorial = factorial * j
sum_of_digits = 0
counter = len(str(factorial))
while counter+1 > 0:
  smallest_digit = factorial % 10
  sum_of_digits = sum_of_digits + smallest_digit
  factorial = factorial // 10
  counter = counter - 1
print("The sum of the digits of 10! is",sum_of_digits)