# -*- coding: utf-8 -*-
"""Infectious Day 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D_RZRuP-bB81yVUvKlI6fLqPYmLRUBA7
"""

#Justin and Nate A, stochastic modelling day 5
#Jan 26 and Jan 28

#Problems 1 and 2
import random
import matplotlib.pyplot as plt

infectious = 1
list1 = []

def step(n,list3, infected,infectious,infectious_nextstep):
  for i in range (n):
    for l in range (infectious):
      random_variable = random.randint(0,2)
      infectious_nextstep = infectious_nextstep + random_variable
    infectious = infectious_nextstep
    list3.append(infectious)
    infectious_nextstep = 0

eradicated_disease_counter = 0

step(21,list1,1,1,0)

plt.plot(list1)
plt.xlabel("Days")
plt.ylabel("People Infected Now")
plt.title("Pandemic Simulation Run 1 Time")#r₀ of 1
plt.show()
list1= []

for a in range (50):
  step(21,list1,1,1,0)
  plt.plot(list1)
  if list1[-1] == 0:
    eradicated_disease_counter = eradicated_disease_counter + 1
  list1= []


plt.xlabel("Days")
plt.ylabel("People Infected Now")
plt.title("Pandemic Simulation Run 50 Times")#r₀ of 1
plt.show()
print("The disease died out", eradicated_disease_counter, "times out of 50 trials for a percentage of", eradicated_disease_counter / .5, "%")

#Problem 3


r_0 = input("r_0: ")
r_0 = float(r_0)
if r_0 < 1:
  p_0 = 1 - r_0 + 1/3 * r_0
  p_1 = 1/3 * r_0
  p_2 = 1/3 * r_0
elif r_0 > 1:
  p_0 = 1/3 * (2-r_0)
  p_1 = 1/3 * (2-r_0)
  p_2 = 1/3 * (2-r_0) + r_0 - 1
else:
  p_0 = 1/3
  p_1 = 1/3
  p_2 = 1/3

print()

import random
import matplotlib.pyplot as plt
infectious = 1
list1 = []

def step(n,list3, infected,infectious,infectious_nextstep):
  for i in range (n):
    for l in range (infectious):
      random_variable = random.choices([0,1,2],weights=[p_0,p_1,p_2])[0]
      infectious_nextstep = infectious_nextstep + random_variable
    infectious = infectious_nextstep
    list3.append(infectious)
    infectious_nextstep = 0


plt.xlabel("Days")
plt.ylabel("People Infected Now")
plt.title(f"Pandemic Simulation Run 50 Times with R₀ of {r_0}")#r₀ of 1

for a in range (50):
  step(21,list1,1,1,0)
  plt.plot(list1)
  list1= []
plt.show()

#Problem 4
r_0 = float(r_0)
if r_0 < 1:
  p_0 = 1 - r_0 + 1/3 * r_0
  p_1 = 1/3 * r_0
  p_2 = 1/3 * r_0
elif r_0 > 1:
  p_0 = 1/3 * (2-r_0)
  p_1 = 1/3 * (2-r_0)
  p_2 = 1/3 * (2-r_0) + r_0 - 1
else:
  p_0 = 1/3
  p_1 = 1/3
  p_2 = 1/3

import random
import matplotlib.pyplot as plt

infectious = 1
list1 = []

def step(n,list3, infected,infectious,infectious_nextstep,r):
  #the inputs of the function are:
  #n - the number of days you run the simulation for (ex. 20 or 100 days)
  #list3 - was used as the list that had all the data for how many people are infectious
  #infected - how many people are infected to begin with
  #infectious - is how many people are infectious to begin with
  #infectious_nextstep - just a placeholder for the number of people who get infected the next day
  #r - the R₀

  if r < 1:
    p_0 = 1 - r + 1/3 * r
    p_1 = 1/3 * r
    p_2 = 1/3 * r
  elif r > 1:
    p_0 = 1/3 * (2-r)
    p_1 = 1/3 * (2-r)
    p_2 = 1/3 * (2-r) + r - 1
  else:
    p_0 = 1/3
    p_1 = 1/3
    p_2 = 1/3
  for i in range (n):
    for l in range (infectious):
#weights the choices 0, 1, and 2 with p_0,p_1,p_2
      random_variable = random.choices([0,1,2],weights=[p_0,p_1,p_2])[0]
      infectious_nextstep = infectious_nextstep + random_variable
    infectious = infectious_nextstep
    list3.append(infectious)
    infectious_nextstep = 0

print("wait 15 seconds for the data to generate")
print()

eradicated_disease_counter = 0
x = []
y = []

for b in range (20):
  r_0=b/200+0.9 #chose 0.9-1 range for r_0 because under 0.9 it is almost always 100% eradicated so not very interesting data
  plt.title(f"Pandemic Simulation Run 1000 Time with R₀ of {r_0}")
  plt.xlabel("Time (Days)")
  plt.ylabel("People Infected Now")
  for a in range (1000): #run the function 1000 times
    step(101,list1,1,1,0,r_0)
    plt.plot(list1)
    if list1[-1] == 0:
  #if last item in list is 0, that means disease is eradicarted, so we add 1 to eradicated disease counter
      eradicated_disease_counter = eradicated_disease_counter + 1
    list1= []
  #plt.show() #uncomment this line to see all the graphs of each R₀
  #print(f"The disease died out {eradicated_disease_counter/10} % of the time")
  x.append(eradicated_disease_counter / 10) #appends the percent of times the disease died out
  y.append(r_0)
  eradicated_disease_counter = 0 #reset for the next R₀ trial

#creates scatter plot of r_0 and percent eradification of disease
print("An epidemic was simulated 20 times for a disease with R₀ from 0.9, 0.905, 0.91... to 1.")
print("For each R₀, we did 1000 trials and let it run for 100 days to see if the disease died out or spread from 1 person.")
print("What you see here is the graph of the percent of times (out of 1000 trials) that the disease died out compared to the R₀.")
print()
plt.cla() #clears the axis of the individual R₀ trials
plt.plot(y,x)
plt.xlabel("R₀")
plt.ylabel("Disease Eradication %")
plt.title("R₀ vs. Diseases Eradication Percent")
plt.show()