# -*- coding: utf-8 -*-
"""infectious day 12

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rLG1UToNMcTdZTv7iKtf9SlHDWWquiSO
"""

import matplotlib.pyplot as plt

def next_step(*, S_previous, \
              I_previous, \
              R_previous, \
              R0, \
              D, \
              time_step_length):
  #your code here; calculate the next values of S, I, and R,
  #and assign them to the variables S_next, I_next, and R_next

  # S_to_I is the number of people who transition from susceptible to infected in one time step.
  N = S_previous + I_previous + R_previous
  S_to_I = (S_previous * I_previous * R0)/(N*D) * time_step_length
  # I_to_R is the number of people who transition from infected to removed in one time step.
  I_to_R = I_previous/D * time_step_length

  S_next = S_previous - S_to_I
  I_next = S_to_I + I_previous - I_to_R
  R_next = I_to_R + R_previous

  return S_next, I_next, R_next

def SIR(*, S_initial, \
        I_initial, \
        R_initial, \
        R0, \
        D, \
        time_step_length, \
        num_steps):
  time_list = [0]
  susceptible_list = [S_initial]
  infected_list = [I_initial]
  removed_list = [R_initial]

  # tracking variables; initially equal to starting values
  S_next = S_initial
  I_next = I_initial
  R_next = R_initial

  while infected_list[-1] >= 1:
    S_next, I_next, R_next = next_step(S_previous = S_next, \
                                                I_previous = I_next, \
                                                R_previous = R_next, \
                                                R0 = R0, \
                                                D = D, \
                                                time_step_length = time_step_length)
    time_list.append(time_list[-1] + time_step_length)
    susceptible_list.append(S_next)
    infected_list.append(I_next)
    removed_list.append(R_next)

  return time_list, susceptible_list, infected_list, removed_list

def draw_graph(*, time_list, \
               susceptible_list, \
               infected_list, \
               removed_list):
  fig = plt.figure()
  plt.plot(time_list, susceptible_list, label='susceptibles')
  plt.plot(time_list, infected_list, label='infected')
  plt.plot(time_list, removed_list, label='removed')
  plt.xlabel("")
  plt.ylabel("")
  plt.legend(loc='lower right')
  plt.show()
  return

def final_size(*, S_initial, \
        I_initial, \
        R_initial, \
        R0, \
        D, \
        time_step_length, \
        num_steps):
  time_list, susceptible_list, infected_list, removed_list = SIR(S_initial=S_initial, \
        I_initial=I_initial, \
        R_initial=R_initial, \
        R0=R0, \
        D=D, \
        time_step_length=time_step_length, \
        num_steps=num_steps)
  return removed_list[-1]

final_list = []
D_values_list = []

for i in range(1,70):
  last_final_size = final_size(S_initial=99999, \
                               I_initial=1, \
                               R_initial=0, \
                               R0=3, \
                               D=i/10, \
                               time_step_length=1, \
                               num_steps=100)
  final_list.append(last_final_size)
  D_values_list.append(i/10)

fig=plt.figure()
plt.plot(D_values_list, final_list)
plt.xlabel("D")
plt.ylabel("Final Size")
plt.title("Final Size Vs. D, R0 = 3")
plt.show()

final_list = []
R0_values_list = []

for i in range(9,40):
  last_final_size = final_size(S_initial=99999, \
                               I_initial=1, \
                               R_initial=0, \
                               R0=i/10, \
                               D=5, \
                               time_step_length=1, \
                               num_steps=100)
  final_list.append(last_final_size)
  R0_values_list.append(i/10)

fig=plt.figure()
plt.plot(R0_values_list, final_list)
plt.xlabel("R0")
plt.ylabel("Final Size")
plt.title("Final Size Vs. R0, D = 5")
plt.show()


R0_x_values = []
D_y_values = []
z_values = []
for i in range(1,70):
  for j in range(9,40):
      last_final_size = final_size(S_initial=99999, \
                                   I_initial=1, \
                                   R_initial=0, \
                                   R0=j/10, \
                                   D=i/10, \
                                   time_step_length=1, \
                                   num_steps=100)
      last_final_size = last_final_size/99999
      R0_x_values.append(j/10)
      D_y_values.append(i/10)
      z_values.append(last_final_size)
fig = plt.figure()
ax = fig.add_subplot(projection='3d')
ax.scatter(R0_x_values, D_y_values, z_values)
plt.title("Final Size Vs. R0 & D")
ax.set_xlabel('R0')
ax.set_ylabel('D')
ax.set_zlabel('Final Size')
ax.set_zlim([0,1])
plt.show()