# -*- coding: utf-8 -*-
"""Infectious Diseases Day 16---Extra Compartmental SIR Models

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cclICvbf6vVpD8hrZ--UV_DmYfZsDAWe

#Infectious Diseases Day 16---Extra Compartmental SIR Models
###Callan and Nate A. 03-09-2026
###Problem 3: SEIR Model
"""

import matplotlib.pyplot as plt

def next_step(*, S_previous, \
              I_previous, \
              R_previous, \
              R0, \
              Dinfected,\
              Dexposed,\
              time_step_length,\
              E_previous):
  #your code here; calculate the next values of S, I, and R,
  #and assign them to the variables S_next, I_next, and R_next

  # S_to_I is the number of people who transition from susceptible to infected in one time step.
  # I_to_R is the number of people who transition from infected to removed in one time step.
  S_to_E = (R0 * S_previous * I_previous) / (Dinfected * (S_previous + I_previous + R_previous + E_previous))
  I_to_R = I_previous / Dinfected
  E_to_I = E_previous / Dexposed

  S_next = S_previous - S_to_E
  I_next = I_previous - I_to_R + E_to_I
  R_next = R_previous + I_to_R
  E_next = E_previous + S_to_E - E_to_I
  return S_next, E_next, I_next, R_next

def SIR(*, S_initial, \
        I_initial, \
        R_initial, \
        R0, \
        Dexposed, \
        time_step_length, \
        num_steps,
        E_initial,
        Dinfected):
  #your code here; call the function next_step and create
  #lists of the times when you calculate steps,
  #the number of susceptible people at every time step,
  #the number of infected people at every time step, and
  #the number of removed people at every time step

  exposed_list = []
  susceptible_list = []
  infected_list = []
  removed_list = []
  time_list = []
  for k in range(0, num_steps, time_step_length):
    time_list.append(k)

  S_previous = S_initial
  I_previous = I_initial
  R_previous = R_initial
  E_previous = E_initial

  for i in (time_list):
    S_next, E_next, I_next, R_next, = next_step(S_previous = S_previous, \
                                                E_previous = E_previous, \
                                                I_previous = I_previous, \
                                                R_previous = R_previous, \
                                                R0 = R0, \
                                                Dinfected = Dinfected, \
                                                Dexposed = Dexposed, \
                                                time_step_length = time_step_length)

    susceptible_list.append(S_previous)
    infected_list.append(I_previous)
    removed_list.append(R_previous)
    exposed_list.append(E_previous)

    S_previous = S_next
    I_previous = I_next
    R_previous = R_next
    E_previous = E_next


  return time_list, susceptible_list, exposed_list, infected_list, removed_list

time_list, susceptible_list, exposed_list, infected_list, removed_list = SIR(S_initial = 99999, \
                                                                             E_initial = 0, \
                                                                             I_initial = 1, \
                                                                             R_initial = 0, \
                                                                             R0 = 3, \
                                                                             Dexposed = 5, \
                                                                             Dinfected = 5, \
                                                                             time_step_length = 1, \
                                                                             num_steps = 200)


def draw_graph(*, time_list, \
               susceptible_list,\
               exposed_list,\
               infected_list, \
               removed_list):
  fig = plt.figure()
  plt.plot(time_list, susceptible_list, label='susceptibles')
  plt.plot(time_list, removed_list, label='removed')
  plt.plot(time_list, infected_list, label='infected')
  plt.plot(time_list, exposed_list, label='exposed')
  plt.xlabel("Time (days)")
  plt.ylabel("Each Group Population")
  plt.legend(loc='lower right')
  plt.title("SEIR Model")
  plt.show()
  return

draw_graph(time_list = time_list, susceptible_list = susceptible_list, exposed_list = exposed_list, infected_list = infected_list, removed_list = removed_list)
print("R_0 = 3, D_Exposed = 5, D_Infectious = 5")

"""###Problem 6: SEIRS Model"""

import matplotlib.pyplot as plt

def next_step(*, S_previous, \
              I_previous, \
              R_previous, \
              R0, \
              Dinfected,\
              Dexposed,\
              time_step_length,\
              E_previous,
              D_removed):
  #your code here; calculate the next values of S, I, and R,
  #and assign them to the variables S_next, I_next, and R_next

  # S_to_I is the number of people who transition from susceptible to infected in one time step.
  # I_to_R is the number of people who transition from infected to removed in one time step.
  S_to_E = (R0 * S_previous * I_previous) / (Dinfected * (S_previous + I_previous + R_previous + E_previous))
  I_to_R = I_previous / Dinfected
  E_to_I = E_previous / Dexposed
  R_to_S = R_previous / D_removed

  S_next = S_previous - S_to_E + R_to_S
  I_next = I_previous - I_to_R + E_to_I
  R_next = R_previous + I_to_R - R_to_S
  E_next = E_previous + S_to_E - E_to_I
  return S_next, E_next, I_next, R_next

def SIR(*, S_initial, \
        I_initial, \
        R_initial, \
        R0, \
        Dexposed, \
        time_step_length, \
        num_steps,
        E_initial,
        Dinfected,
        D_removed):
  #your code here; call the function next_step and create
  #lists of the times when you calculate steps,
  #the number of susceptible people at every time step,
  #the number of infected people at every time step, and
  #the number of removed people at every time step

  exposed_list = []
  susceptible_list = []
  infected_list = []
  removed_list = []
  time_list = []
  for k in range(0, num_steps, time_step_length):
    time_list.append(k)

  S_previous = S_initial
  I_previous = I_initial
  R_previous = R_initial
  E_previous = E_initial

  for i in (time_list):
    S_next, E_next, I_next, R_next = next_step(S_previous = S_previous, \
                                                E_previous = E_previous, \
                                                I_previous = I_previous, \
                                                R_previous = R_previous, \
                                                R0 = R0, \
                                                Dinfected = Dinfected, \
                                                Dexposed = Dexposed, \
                                                time_step_length = time_step_length,
                                                D_removed = D_removed)
    susceptible_list.append(S_previous)
    infected_list.append(I_previous)
    removed_list.append(R_previous)
    exposed_list.append(E_previous)

    S_previous = S_next
    I_previous = I_next
    R_previous = R_next
    E_previous = E_next


  return time_list, susceptible_list, exposed_list, infected_list, removed_list

time_list, susceptible_list, exposed_list, infected_list, removed_list = SIR(S_initial = 99999, \
                                                                             E_initial = 0, \
                                                                             I_initial = 1, \
                                                                             R_initial = 0, \
                                                                             R0 = 7, \
                                                                             Dexposed = 5, \
                                                                             Dinfected = 5, \
                                                                             time_step_length = 1, \
                                                                             num_steps = 250, \
                                                                             D_removed = 120)



def draw_graph(*, time_list, \
               susceptible_list,\
               exposed_list,\
               infected_list, \
               removed_list):
  fig = plt.figure()
  plt.plot(time_list, susceptible_list, label='susceptibles')
  plt.plot(time_list, removed_list, label='removed')
  plt.plot(time_list, infected_list, label='infected')
  plt.plot(time_list, exposed_list, label='exposed')
  plt.xlabel("Time (days)")
  plt.ylabel("Each Group Population")
  plt.legend(loc='lower right')
  plt.title("SEIRS Model")
  plt.show()
  return

draw_graph(time_list = time_list, susceptible_list = susceptible_list, exposed_list = exposed_list, infected_list = infected_list, removed_list = removed_list)
print("R_0 = 3, D_Exposed = 5, D_Infectious = 5, D_Removed = 120")